"""Arrival process (spec Section 5 ARRIVALS: Poisson base + diurnal + bursts).

A non-homogeneous Poisson process with instantaneous rate

    lambda(t) = base_rate * (1 + amplitude * sin(2*pi*t/period + phase)) * burst(t)

where burst(t) is a multiplier during pre-scheduled burst episodes and 1 otherwise.
Arrival times are generated by thinning (Lewis-Shedler): propose candidates from a
homogeneous process at the peak rate lambda_max and accept candidate t with
probability lambda(t) / lambda_max. This is exact for any bounded rate function.

House style: hyphens only (D-026).
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np


@dataclass(frozen=True)
class DiurnalSpec:
    period_s: float
    amplitude: float          # must be < 1 so the rate stays positive
    phase_s: float

    @classmethod
    def from_config(cls, cfg: dict) -> "DiurnalSpec":
        return cls(period_s=float(cfg["period_s"]),
                   amplitude=float(cfg["amplitude"]),
                   phase_s=float(cfg["phase_s"]))

    def factor(self, t: float) -> float:
        phase = 2.0 * math.pi * self.phase_s / self.period_s
        return 1.0 + self.amplitude * math.sin(2.0 * math.pi * t / self.period_s + phase)


@dataclass(frozen=True)
class BurstSpec:
    rate_multiplier: float
    mean_duration_s: float
    episodes_per_day: float

    @classmethod
    def from_config(cls, cfg: dict) -> "BurstSpec":
        return cls(rate_multiplier=float(cfg["rate_multiplier"]),
                   mean_duration_s=float(cfg["mean_duration_s"]),
                   episodes_per_day=float(cfg["episodes_per_day"]))


@dataclass(frozen=True)
class ArrivalSpec:
    base_rate_per_s: float
    diurnal: DiurnalSpec
    burst: BurstSpec

    @classmethod
    def from_config(cls, cfg: dict) -> "ArrivalSpec":
        return cls(base_rate_per_s=float(cfg["base_rate_per_s"]),
                   diurnal=DiurnalSpec.from_config(cfg["diurnal"]),
                   burst=BurstSpec.from_config(cfg["burst"]))


def generate_burst_intervals(
    spec: ArrivalSpec, rng: np.random.Generator, horizon_s: float,
) -> list[tuple[float, float]]:
    """Pre-schedule burst episodes over [0, horizon]: (start, end) intervals.

    Episode count is Poisson with mean episodes_per_day * days; starts are uniform;
    durations are exponential with the configured mean. Overlaps are allowed (they
    simply do not stack -- burst(t) is a single multiplier when inside any episode).
    """
    days = horizon_s / 86400.0
    expected = spec.burst.episodes_per_day * days
    n_episodes = int(rng.poisson(expected)) if expected > 0 else 0
    intervals: list[tuple[float, float]] = []
    for _ in range(n_episodes):
        start = float(rng.uniform(0.0, horizon_s))
        duration = float(rng.exponential(spec.burst.mean_duration_s))
        intervals.append((start, min(start + duration, horizon_s)))
    intervals.sort()
    return intervals


def _in_burst(t: float, intervals: list[tuple[float, float]]) -> bool:
    # Linear scan is fine at SG2 validation scale; the grid runner uses modest
    # horizons per cell. A sorted-interval bisect is a trivial later optimization.
    for start, end in intervals:
        if start <= t <= end:
            return True
        if start > t:
            break
    return False


def rate_at(t: float, spec: ArrivalSpec,
            burst_intervals: list[tuple[float, float]]) -> float:
    """Instantaneous arrival rate lambda(t)."""
    burst_factor = spec.burst.rate_multiplier if _in_burst(t, burst_intervals) else 1.0
    return spec.base_rate_per_s * spec.diurnal.factor(t) * burst_factor


def peak_rate(spec: ArrivalSpec) -> float:
    """Upper bound lambda_max used for thinning."""
    return spec.base_rate_per_s * (1.0 + spec.diurnal.amplitude) * spec.burst.rate_multiplier


def arrival_times(
    spec: ArrivalSpec, rng: np.random.Generator, horizon_s: float,
    burst_intervals: list[tuple[float, float]],
) -> list[float]:
    """Generate sorted arrival times on [0, horizon] by thinning."""
    lam_max = peak_rate(spec)
    times: list[float] = []
    t = 0.0
    while True:
        t += float(rng.exponential(1.0 / lam_max))
        if t > horizon_s:
            break
        if rng.random() < rate_at(t, spec, burst_intervals) / lam_max:
            times.append(t)
    return times
