"""Metrics collection (spec Section 2, full set).

Everything spec Section 2 defines, computed per run:

  PRIMARY (H1): goodput per PROVISIONED GPU-hour -- value-weighted completed flows
    over the GPU-hours the cluster was provisioned for (not the hours it used), so
    idle-but-reserved capacity lowers our own score with no separate fudge factor.
  SECONDARY:
    - p95/p99 flow-completion latency for the agentic classes (the tail),
    - p95 time-to-first-token and inter-token latency for interactive traffic (the
      guardrail spec Section 3 pins the reservation discipline against),
    - reserved-idle fraction (stranding),
    - preemption / abandonment / degradation counts,
    - wasted-computation fraction (tokens generated by flows that never complete).
  H2: served-value fraction (completed value over offered value) -- the y-axis of
    the graceful-degradation curve.
  H3: per-class arrival and completion counts, so the compliant-flow completion rate
    under runaway injection can be computed across runs.

A warmup cutoff discards the initial transient: only intervals, arrivals, and
completions at or after `warmup_s` contribute.

Latency modelling notes (declared, so the fidelity caveat is explicit):
  * TTFT is measured from flow arrival to the first invocation entering decode
    (admission wait + prefill). The single first-token generation time is a rate-
    dependent sub-millisecond term and is not separately added.
  * ITL is the mean inter-token time over an invocation's decode span
    (decode duration / output tokens).
Both are consistent across policies, so the RELATIVE guardrail comparison the spec
requires is unaffected.

House style: hyphens only (D-026).
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np


def _pct(values: list[float], q: float) -> float:
    """The q-th percentile (q in [0,100]) of a list, or 0.0 if empty."""
    if not values:
        return 0.0
    return float(np.percentile(np.asarray(values, dtype=float), q))


@dataclass
class RunResult:
    """Aggregate results of one simulation run (spec Section 2, full set)."""

    horizon_s: float
    warmup_s: float
    measure_window_s: float

    arrivals: int = 0
    admissions: int = 0
    rejections: int = 0
    completions: int = 0            # flows completed within the measure window

    # Preemption accounting (SG3).
    preemptions: int = 0
    recompute_preemptions: int = 0
    swap_preemptions: int = 0
    wasted_prefill_tokens: float = 0.0   # re-prefilled tokens after recompute

    # PRIMARY METRIC (spec Section 2 / Section 3): goodput per provisioned GPU-hour.
    completed_value: float = 0.0
    provisioned_gpu_hours: float = 0.0
    goodput_per_gpu_hour: float = 0.0

    # H2: served-value fraction (completed value / offered value).
    offered_value: float = 0.0
    served_value_fraction: float = 0.0

    # Tail latency (agentic classes) and the interactive guardrail.
    p95_flow_completion_s: float = 0.0
    p99_flow_completion_s: float = 0.0
    p95_ttft_s: float = 0.0            # interactive -- the guardrail
    p95_itl_s: float = 0.0            # interactive
    mean_ttft_s: float = 0.0

    # Wasted computation (spec Section 2): tokens generated by flows that never
    # complete, as a fraction of all generated tokens.
    total_generated_tokens: float = 0.0
    useful_generated_tokens: float = 0.0
    wasted_computation_fraction: float = 0.0

    # Reservation accounting (SG4).
    reservations: int = 0
    abandonments: int = 0                # flows killed by budget exhaustion
    degradations: int = 0
    reserved_idle_fraction: float = 0.0  # stranding: pinned slot-time that sat idle
    pinned_slot_seconds: float = 0.0
    pinned_active_seconds: float = 0.0

    # H3: per-class arrival and completion counts. Key is "cls|runaway".
    arrivals_by_class: dict = field(default_factory=dict)
    completions_by_class: dict = field(default_factory=dict)

    # Little's law estimators (steady state, post-warmup).
    time_avg_in_system: float = 0.0     # L
    throughput_per_s: float = 0.0       # lambda (completions / measure window)
    mean_sojourn_s: float = 0.0         # W

    # Utilization.
    mean_utilization: float = 0.0
    per_device_utilization: list[float] = field(default_factory=list)

    @property
    def littles_law_lhs(self) -> float:
        return self.time_avg_in_system

    @property
    def littles_law_rhs(self) -> float:
        return self.throughput_per_s * self.mean_sojourn_s

    def compliant_completion_rate(self, compliant_key: str = "agentic|0") -> float:
        """Completion rate for compliant (non-runaway) agentic flows (H3)."""
        arrived = self.arrivals_by_class.get(compliant_key, 0)
        done = self.completions_by_class.get(compliant_key, 0)
        return done / arrived if arrived > 0 else 0.0


class MetricsCollector:
    """Accumulates time-integrated and per-flow statistics during a run."""

    def __init__(self, horizon_s: float, warmup_s: float, num_devices: int) -> None:
        self._horizon = float(horizon_s)
        self._warmup = float(warmup_s)
        self._num_devices = num_devices

        self.arrivals = 0
        self.admissions = 0
        self.rejections = 0
        self.completions = 0

        self.preemptions = 0
        self.recompute_preemptions = 0
        self.swap_preemptions = 0
        self.wasted_prefill_tokens = 0.0

        # Reservation accounting (SG4).
        self.reservations = 0
        self.abandonments = 0
        self.degradations = 0
        self._pinned = 0
        self._pinned_active = 0
        self._pin_last_t = 0.0
        self._pinned_area = 0.0
        self._pinned_active_area = 0.0

        # In-system count integral (post-warmup).
        self._in_system = 0
        self._last_change_t = 0.0
        self._area_in_system = 0.0

        # Per-flow completion stats (post-warmup completions only).
        self._sojourn_sum = 0.0
        self._completed_value = 0.0
        self._offered_value = 0.0
        self._agentic_completion_s: list[float] = []
        self._interactive_ttft_s: list[float] = []
        self._interactive_itl_s: list[float] = []
        self._ttft_sum = 0.0
        self._ttft_n = 0

        # Wasted computation.
        self._total_generated = 0.0
        self._useful_generated = 0.0

        # H3 per-class accounting.
        self._arrivals_by_class: dict = {}
        self._completions_by_class: dict = {}

        # Per-device busy-time integral (post-warmup).
        self._device_busy = [0.0] * num_devices
        self._device_busy_since: list[float | None] = [None] * num_devices

    # --- helpers ----------------------------------------------------------------

    def _clip(self, t: float) -> float:
        if t < self._warmup:
            return self._warmup
        if t > self._horizon:
            return self._horizon
        return t

    def _accumulate_in_system(self, now: float) -> None:
        lo = self._clip(self._last_change_t)
        hi = self._clip(now)
        if hi > lo:
            self._area_in_system += self._in_system * (hi - lo)
        self._last_change_t = now

    @staticmethod
    def _key(cls: str, is_runaway: bool) -> str:
        return f"{cls}|{int(is_runaway)}"

    # --- flow lifecycle ---------------------------------------------------------

    def on_arrival(self, now: float, value_weight: float = 1.0,
                   cls: str = "default", is_runaway: bool = False) -> None:
        self.arrivals += 1
        if now >= self._warmup:
            # Offered value uses the flow's ORIGINAL weight (before any degradation),
            # so the served-value fraction measures value shed to BOTH non-completion
            # and degradation.
            self._offered_value += value_weight
            key = self._key(cls, is_runaway)
            self._arrivals_by_class[key] = self._arrivals_by_class.get(key, 0) + 1

    def on_admit(self, now: float) -> None:
        self._accumulate_in_system(now)
        self.admissions += 1
        self._in_system += 1

    def on_reject(self, now: float) -> None:
        self.rejections += 1

    def on_preemption(self, now: float, swapped: bool) -> None:
        self.preemptions += 1
        if swapped:
            self.swap_preemptions += 1
        else:
            self.recompute_preemptions += 1

    def on_reprefill(self, now: float, tokens: float) -> None:
        """Re-prefill overhead after a recompute preemption (distinct from the
        spec's wasted-computation metric, which is about non-completing flows)."""
        self.wasted_prefill_tokens += tokens

    def on_tokens_decoded(self, now: float, tokens: float) -> None:
        """Total output tokens generated across the cluster (post-warmup)."""
        if now >= self._warmup and tokens > 0:
            self._total_generated += tokens

    # --- reservation accounting (SG4) ---------------------------------------------

    def _accumulate_pins(self, now: float) -> None:
        lo = self._clip(self._pin_last_t)
        hi = self._clip(now)
        if hi > lo:
            self._pinned_area += self._pinned * (hi - lo)
            self._pinned_active_area += self._pinned_active * (hi - lo)
        self._pin_last_t = now

    def on_pin_change(self, now: float, delta: int) -> None:
        self._accumulate_pins(now)
        self._pinned += delta
        if delta > 0:
            self.reservations += delta

    def on_pin_active_change(self, now: float, delta: int) -> None:
        self._accumulate_pins(now)
        self._pinned_active += delta

    def on_abandonment(self, now: float) -> None:
        self._accumulate_in_system(now)
        self._in_system -= 1
        self.abandonments += 1

    def on_degradation(self, now: float) -> None:
        self.degradations += 1

    def on_flow_complete(self, now: float, sojourn_s: float, value_weight: float,
                         cls: str, is_runaway: bool, ttft_s: float | None,
                         itl_s: float | None, generated_tokens: float) -> None:
        self._accumulate_in_system(now)
        self._in_system -= 1
        if now < self._warmup:
            return
        self.completions += 1
        self._sojourn_sum += sojourn_s
        self._completed_value += value_weight
        self._useful_generated += generated_tokens

        key = self._key(cls, is_runaway)
        self._completions_by_class[key] = self._completions_by_class.get(key, 0) + 1

        if cls == "interactive":
            if ttft_s is not None:
                self._interactive_ttft_s.append(ttft_s)
                self._ttft_sum += ttft_s
                self._ttft_n += 1
            if itl_s is not None:
                self._interactive_itl_s.append(itl_s)
        else:
            self._agentic_completion_s.append(sojourn_s)

    # --- device busy accounting -------------------------------------------------

    def on_device_busy_start(self, now: float, device_id: int) -> None:
        if self._device_busy_since[device_id] is None:
            self._device_busy_since[device_id] = now

    def on_device_busy_end(self, now: float, device_id: int) -> None:
        since = self._device_busy_since[device_id]
        if since is not None:
            lo = self._clip(since)
            hi = self._clip(now)
            if hi > lo:
                self._device_busy[device_id] += (hi - lo)
            self._device_busy_since[device_id] = None

    # --- finalize ---------------------------------------------------------------

    def finalize(self, now: float) -> RunResult:
        self._accumulate_in_system(now)
        self._accumulate_pins(now)
        for d in range(self._num_devices):
            if self._device_busy_since[d] is not None:
                self.on_device_busy_end(now, d)

        window = max(self._clip(now) - self._warmup, 1e-12)
        per_dev_util = [busy / window for busy in self._device_busy]
        mean_util = sum(per_dev_util) / len(per_dev_util) if per_dev_util else 0.0

        throughput = self.completions / window
        mean_sojourn = (self._sojourn_sum / self.completions
                        if self.completions > 0 else 0.0)
        l_avg = self._area_in_system / window

        provisioned_gpu_hours = self._num_devices * window / 3600.0
        goodput = (self._completed_value / provisioned_gpu_hours
                   if provisioned_gpu_hours > 0 else 0.0)

        served_value_fraction = (self._completed_value / self._offered_value
                                 if self._offered_value > 0 else 0.0)
        wasted_computation_fraction = (
            (self._total_generated - self._useful_generated) / self._total_generated
            if self._total_generated > 0 else 0.0)

        return RunResult(
            horizon_s=self._horizon,
            warmup_s=self._warmup,
            measure_window_s=window,
            arrivals=self.arrivals,
            admissions=self.admissions,
            rejections=self.rejections,
            completions=self.completions,
            preemptions=self.preemptions,
            recompute_preemptions=self.recompute_preemptions,
            swap_preemptions=self.swap_preemptions,
            wasted_prefill_tokens=self.wasted_prefill_tokens,
            completed_value=self._completed_value,
            provisioned_gpu_hours=provisioned_gpu_hours,
            goodput_per_gpu_hour=goodput,
            offered_value=self._offered_value,
            served_value_fraction=served_value_fraction,
            p95_flow_completion_s=_pct(self._agentic_completion_s, 95),
            p99_flow_completion_s=_pct(self._agentic_completion_s, 99),
            p95_ttft_s=_pct(self._interactive_ttft_s, 95),
            p95_itl_s=_pct(self._interactive_itl_s, 95),
            mean_ttft_s=(self._ttft_sum / self._ttft_n if self._ttft_n else 0.0),
            total_generated_tokens=self._total_generated,
            useful_generated_tokens=self._useful_generated,
            wasted_computation_fraction=max(0.0, wasted_computation_fraction),
            reservations=self.reservations,
            abandonments=self.abandonments,
            degradations=self.degradations,
            reserved_idle_fraction=(
                1.0 - self._pinned_active_area / self._pinned_area
                if self._pinned_area > 0 else 0.0),
            pinned_slot_seconds=self._pinned_area,
            pinned_active_seconds=self._pinned_active_area,
            arrivals_by_class=dict(self._arrivals_by_class),
            completions_by_class=dict(self._completions_by_class),
            time_avg_in_system=l_avg,
            throughput_per_s=throughput,
            mean_sojourn_s=mean_sojourn,
            mean_utilization=mean_util,
            per_device_utilization=per_dev_util,
        )
