"""Write the tuning report: the grid as searched, and what it chose.

The report is a deliverable, not a log. It has to let a reviewer check that we did
not tune ourselves an advantage: the budget each policy got, the seeds it was tuned
on, the seeds it was scored on, and the parameters that came out.

Run:  make tune   (from code/sim)

House style: hyphens only (D-026).
"""

from __future__ import annotations

import json
from pathlib import Path

from .harness import (
    check_equal_budget,
    check_seed_split,
    grid_points,
    load_tuning_config,
    run_tuning,
)

_OUT = Path(__file__).resolve().parent.parent / "docs" / "TUNING_REPORT.md"
# Machine-readable tuned parameters the grid runner consumes.
_PARAMS_OUT = Path(__file__).resolve().parent.parent / "configs" / "tuned_params.json"


def write_tuned_params(results, path: Path = _PARAMS_OUT) -> Path:
    """Emit {policy: {family: chosen_params}} for the grid runner (spec Section 4)."""
    out: dict = {}
    for r in results:
        out.setdefault(r.policy, {})[r.family] = r.best_params
    path.write_text(json.dumps(out, indent=2, sort_keys=True), encoding="utf-8")
    return path


def _fmt_params(params: dict) -> str:
    if not params:
        return "_(no parameters -- the no-control floor)_"
    return ", ".join(f"`{k}={v}`" for k, v in sorted(params.items()))


def write_report(results, tuning_cfg, path: Path = _OUT) -> Path:
    cfg = tuning_cfg
    budget = cfg["budget"]
    validation = cfg["seeds"]["validation"]
    heldout = cfg["seeds"]["heldout"]

    lines: list[str] = []
    lines.append("# T-055 Tuning Report (SG5)")
    lines.append("")
    lines.append("Generated by `make tune`. Do not hand-edit.")
    lines.append("")
    lines.append("Baseline fairness protocol, spec Section 4: *\"Each baseline gets a "
                 "tuning budget equal to ours: a pre-registered grid over its policy "
                 "parameters, tuned per workload family on validation seeds, "
                 "evaluated on held-out seeds.\"*")
    lines.append("")
    lines.append("**Objective:** goodput per provisioned GPU-hour (spec Section 2) -- "
                 "the primary metric, which already charges the reservation discipline "
                 "for the capacity its pins strand.")
    lines.append("")

    # --- the protocol, stated up front ---
    lines.append("## The protocol")
    lines.append("")
    lines.append(f"- **Equal budget:** {budget} grid points per tunable policy. "
                 "Enforced by test; the build fails if any grid differs.")
    lines.append(f"- **Validation seeds (tuner sees these):** {validation}")
    lines.append(f"- **Held-out seeds (tuner never sees these):** {heldout}")
    lines.append("- **Disjoint:** asserted by test.")
    cell = cfg["cell"]
    lines.append(f"- **Cell:** {cell['cluster']['num_devices']} devices x "
                 f"{cell['cluster']['device']['max_concurrent_decodes']} slots, "
                 f"horizon {cell['horizon_s']}s, warmup {cell['warmup_s']}s.")
    untuned = cfg.get("untuned_policies", [])
    if untuned:
        lines.append(f"- **Untuned by design:** {', '.join(untuned)} "
                     "(the no-control floor has no parameters).")
    lines.append("")

    # --- the grid as pre-registered ---
    lines.append("## The grid, as pre-registered")
    lines.append("")
    lines.append("| Policy | Axes | Points |")
    lines.append("|--------|------|--------|")
    for name, axes in cfg["grids"].items():
        axes_str = "; ".join(f"`{k}` = {v}" for k, v in axes.items())
        lines.append(f"| `{name}` | {axes_str} | {len(grid_points(axes))} |")
    lines.append("")

    # --- what it chose ---
    lines.append("## Selected parameters")
    lines.append("")
    lines.append("`validation` is the score the parameters were CHOSEN on. "
                 "`held-out` is the score of those same parameters on seeds the "
                 "tuner never saw -- the honest number.")
    lines.append("")

    families = sorted({r.family for r in results})
    for family in families:
        lines.append(f"### Workload family: `{family}`")
        lines.append("")
        lines.append("| Policy | Chosen parameters | validation | held-out |")
        lines.append("|--------|-------------------|-----------:|---------:|")
        rows = [r for r in results if r.family == family]
        rows.sort(key=lambda r: -r.heldout_score)
        for r in rows:
            lines.append(
                f"| `{r.policy}` | {_fmt_params(r.best_params)} | "
                f"{r.validation_score:.1f} | {r.heldout_score:.1f} |")
        lines.append("")

    lines.append("## What this report is NOT")
    lines.append("")
    lines.append("These are TUNED PARAMETERS, not results. The held-out scores here "
                 "come from a single tuning cell and are not the experiment. The H1 "
                 "verdict is computed on the full pre-registered grid (spec Section 7) "
                 "with bootstrap CIs, per-cell best-baseline selection, and the "
                 "corner-cell exclusions -- that is SG7, and nothing here should be "
                 "quoted as an outcome.")
    lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def main() -> None:
    cfg = load_tuning_config()

    # Fail loudly before spending any compute if the protocol itself is broken.
    check_equal_budget(cfg)
    check_seed_split(cfg)

    n_families = len(cfg["families"])
    n_policies = len(cfg["grids"]) + len(cfg.get("untuned_policies", []))
    print(f"Tuning {n_policies} policies x {n_families} families "
          f"x {cfg['budget']} grid points x "
          f"{len(cfg['seeds']['validation'])} validation seeds ...")

    results = run_tuning(cfg)
    path = write_report(results, cfg)
    params_path = write_tuned_params(results)
    print(f"\nWrote {path}")
    print(f"Wrote {params_path}")

    for family in sorted({r.family for r in results}):
        print(f"\n--- {family} ---")
        rows = sorted((r for r in results if r.family == family),
                      key=lambda r: -r.heldout_score)
        for r in rows:
            print(f"  {r.policy:<16} held-out {r.heldout_score:10.1f}  "
                  f"{r.best_params}")


if __name__ == "__main__":
    main()
